### ISSUE TITLE
Document SCEP support

### ISSUE THREAD

**Issue by tashian** [smallstep/docs-old#85]
See smallstep/certificates#506 for details

**Comment by tashian** [comment]
@hslatman @dopey @maraino should we wait for SCEP support in `step ca provisioner` before documenting this, or go ahead and document as is?

**Comment by maraino** [comment]
I think we can start as it is, and then change it later if necessary.

**Comment by hslatman** [comment]
I agree with @maraino, but I have to add that the current SCEP support is quite minimal. It is working for several users and some use cases, however, so it is good to be clear about that current state and what `step-ca` can (already) do and what not. 

The main things up for improvement (IMO):

1. Support for multiple challenge secrets. Currently a single one can be configured in `ca.json`. Challenge secrets are conceptually fairly similar to ACME EAB credentials, so an improvement to the current setup could be similar to how we handle those keys (in `step beta ca provisioner`), so that every client uses their own secret.
2. Intermediate configuration. As SCEP (usually) requires RSA (en|de)cryption, the intermediate currently needs to be configured with an RSA key. This requires some manual steps and results in, in the most basic setup, `step-ca` using this RSA for all its provisioners. Usage of multiple intermediates/chains was discussed internally at some point. These improvements could be built on top of that.

That said, let me know if I can help with these docs.

**Comment by maraino** [comment]
If we ever add support for multiple challenges secretes we might also want to use a different key for encryption/decryption
